// Code generated by github.com/maaft/gqlgenc, DO NOT EDIT.

package hasuragql

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/maaft/gqlgenc/client"
	"github.com/maaft/gqlgenc/client/transport"
)

type Client struct {
	Client *client.Client
}

// OPERATION: CheckProjectGroup
type CheckProjectGroup struct {
	Projects []CheckProjectGroup_Projects "json:\"projects\""
}

// OPERATION: CheckProjectGroup.projects
type CheckProjectGroup_Projects struct {
	ID uuid.UUID "json:\"id\""
}

// OPERATION: CheckUserGroupMembership
type CheckUserGroupMembership struct {
	GroupMemberships []CheckUserGroupMembership_GroupMemberships "json:\"group_memberships\""
}

// OPERATION: CheckUserGroupMembership.group_memberships
type CheckUserGroupMembership_GroupMemberships struct {
	UserID uuid.UUID "json:\"user_id\""
}

// OPERATION: GetProjectForUser
type GetProjectForUser struct {
	Projects []GetProjectForUser_Projects "json:\"projects\""
}

// OPERATION: GetProjectForUser.projects
type GetProjectForUser_Projects struct {
	ID      uuid.UUID "json:\"id\""
	GroupID uuid.UUID "json:\"group_id\""
}

// OPERATION: GetUserByEmail
type GetUserByEmail struct {
	Users []GetUserByEmail_Users "json:\"users\""
}

// OPERATION: GetUserByEmail.users
type GetUserByEmail_Users struct {
	ID             uuid.UUID "json:\"id\""
	Email          string    "json:\"email\""
	DisplayName    string    "json:\"display_name\""
	PasswordHash   string    "json:\"password_hash\""
	DefaultGroupID uuid.UUID "json:\"default_group_id\""
}

// OPERATION: InsertImageNodeAndData
type InsertImageNodeAndData struct {
	InsertNodesOne *InsertImageNodeAndData_InsertNodesOne "json:\"insert_nodes_one\""
}

// OPERATION: InsertImageNodeAndData.insert_nodes_one
type InsertImageNodeAndData_InsertNodesOne struct {
	ID    uuid.UUID                                    "json:\"id\""
	Image *InsertImageNodeAndData_InsertNodesOne_Image "json:\"image\""
}

// OPERATION: InsertImageNodeAndData.insert_nodes_one.image
type InsertImageNodeAndData_InsertNodesOne_Image struct {
	FileID uuid.UUID "json:\"file_id\""
}

// OPERATION: UpdateUserLastLogin
type UpdateUserLastLogin struct {
	UpdateUsersByPk *UpdateUserLastLogin_UpdateUsersByPk "json:\"update_users_by_pk\""
}

// OPERATION: UpdateUserLastLogin.update_users_by_pk
type UpdateUserLastLogin_UpdateUsersByPk struct {
	ID uuid.UUID "json:\"id\""
}

// Pointer helpers
func UUIDPtr(v uuid.UUID) *uuid.UUID {
	return &v
}

const CheckProjectGroupDocument = `query CheckProjectGroup ($projectId: uuid!, $groupId: uuid!) {
	projects(where: {id:{_eq:$projectId},group_id:{_eq:$groupId}}, limit: 1) {
		id
	}
}
`

func (Ξc *Client) CheckProjectGroup(ctх context.Context, projectID uuid.UUID, groupID uuid.UUID, overrideRequestOptions ...transport.HttpRequestOption) (*CheckProjectGroup, transport.OperationResponse, error) {
	Ξvars := map[string]interface{}{
		"projectId": projectID,
		"groupId":   groupID,
	}

	{
		var data CheckProjectGroup
		res, err := Ξc.Client.Query(ctх, "CheckProjectGroup", CheckProjectGroupDocument, Ξvars, &data, overrideRequestOptions...)
		if err != nil {
			return nil, transport.OperationResponse{}, err
		}

		return &data, res, nil
	}
}

const CheckUserGroupMembershipDocument = `query CheckUserGroupMembership ($userId: uuid!, $groupId: uuid!) {
	group_memberships(where: {user_id:{_eq:$userId},group_id:{_eq:$groupId}}, limit: 1) {
		user_id
	}
}
`

func (Ξc *Client) CheckUserGroupMembership(ctх context.Context, userID uuid.UUID, groupID uuid.UUID, overrideRequestOptions ...transport.HttpRequestOption) (*CheckUserGroupMembership, transport.OperationResponse, error) {
	Ξvars := map[string]interface{}{
		"userId":  userID,
		"groupId": groupID,
	}

	{
		var data CheckUserGroupMembership
		res, err := Ξc.Client.Query(ctх, "CheckUserGroupMembership", CheckUserGroupMembershipDocument, Ξvars, &data, overrideRequestOptions...)
		if err != nil {
			return nil, transport.OperationResponse{}, err
		}

		return &data, res, nil
	}
}

const GetProjectForUserDocument = `query GetProjectForUser ($projectId: uuid!, $userId: uuid!) {
	projects(where: {id:{_eq:$projectId},group:{memberships:{user_id:{_eq:$userId}}}}, limit: 1) {
		id
		group_id
	}
}
`

func (Ξc *Client) GetProjectForUser(ctх context.Context, projectID uuid.UUID, userID uuid.UUID, overrideRequestOptions ...transport.HttpRequestOption) (*GetProjectForUser, transport.OperationResponse, error) {
	Ξvars := map[string]interface{}{
		"projectId": projectID,
		"userId":    userID,
	}

	{
		var data GetProjectForUser
		res, err := Ξc.Client.Query(ctх, "GetProjectForUser", GetProjectForUserDocument, Ξvars, &data, overrideRequestOptions...)
		if err != nil {
			return nil, transport.OperationResponse{}, err
		}

		return &data, res, nil
	}
}

const GetUserByEmailDocument = `query GetUserByEmail ($email: String!) {
	users(where: {email:{_eq:$email}}, limit: 1) {
		id
		email
		display_name
		password_hash
		default_group_id
	}
}
`

func (Ξc *Client) GetUserByEmail(ctх context.Context, email string, overrideRequestOptions ...transport.HttpRequestOption) (*GetUserByEmail, transport.OperationResponse, error) {
	Ξvars := map[string]interface{}{
		"email": email,
	}

	{
		var data GetUserByEmail
		res, err := Ξc.Client.Query(ctх, "GetUserByEmail", GetUserByEmailDocument, Ξvars, &data, overrideRequestOptions...)
		if err != nil {
			return nil, transport.OperationResponse{}, err
		}

		return &data, res, nil
	}
}

const InsertImageNodeAndDataDocument = `mutation InsertImageNodeAndData ($nodeId: uuid!, $projectId: uuid!, $parentId: uuid, $groupId: uuid!, $createdBy: uuid!, $name: String!, $createdAt: timestamptz!, $mimeType: String!, $sizeBytes: bigint!, $storageKey: String!, $thumbnailKey: String!) {
	insert_nodes_one(object: {id:$nodeId,project_id:$projectId,parent_id:$parentId,group_id:$groupId,created_by:$createdBy,node_type:"image",name:$name,created_at:$createdAt,image:{data:{mime_type:$mimeType,size_bytes:$sizeBytes,storage_key:$storageKey,thumbnail_key:$thumbnailKey,created_at:$createdAt}}}) {
		id
		image {
			file_id
		}
	}
}
`

func (Ξc *Client) InsertImageNodeAndData(ctх context.Context, nodeID uuid.UUID, projectID uuid.UUID, parentID *uuid.UUID, groupID uuid.UUID, createdBy uuid.UUID, name string, createdAt time.Time, mimeType string, sizeBytes int64, storageKey string, thumbnailKey string, overrideRequestOptions ...transport.HttpRequestOption) (*InsertImageNodeAndData, transport.OperationResponse, error) {
	Ξvars := map[string]interface{}{
		"nodeId":       nodeID,
		"projectId":    projectID,
		"parentId":     parentID,
		"groupId":      groupID,
		"createdBy":    createdBy,
		"name":         name,
		"createdAt":    createdAt,
		"mimeType":     mimeType,
		"sizeBytes":    sizeBytes,
		"storageKey":   storageKey,
		"thumbnailKey": thumbnailKey,
	}

	{
		var data InsertImageNodeAndData
		res, err := Ξc.Client.Mutation(ctх, "InsertImageNodeAndData", InsertImageNodeAndDataDocument, Ξvars, &data, overrideRequestOptions...)
		if err != nil {
			return nil, transport.OperationResponse{}, err
		}

		return &data, res, nil
	}
}

const UpdateUserLastLoginDocument = `mutation UpdateUserLastLogin ($userId: uuid!, $lastLoginAt: timestamptz!) {
	update_users_by_pk(pk_columns: {id:$userId}, _set: {last_login_at:$lastLoginAt}) {
		id
	}
}
`

func (Ξc *Client) UpdateUserLastLogin(ctх context.Context, userID uuid.UUID, lastLoginAt time.Time, overrideRequestOptions ...transport.HttpRequestOption) (*UpdateUserLastLogin, transport.OperationResponse, error) {
	Ξvars := map[string]interface{}{
		"userId":      userID,
		"lastLoginAt": lastLoginAt,
	}

	{
		var data UpdateUserLastLogin
		res, err := Ξc.Client.Mutation(ctх, "UpdateUserLastLogin", UpdateUserLastLoginDocument, Ξvars, &data, overrideRequestOptions...)
		if err != nil {
			return nil, transport.OperationResponse{}, err
		}

		return &data, res, nil
	}
}
