// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateTokenPayload struct {
	Token          string `json:"token"`
	TokenExpiresAt int    `json:"tokenExpiresAt"`
	UserID         string `json:"userId"`
	GroupID        string `json:"groupId"`
	Email          string `json:"email"`
	DisplayName    string `json:"displayName"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}
