package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"errors"
	"fmt"
	"hiring-challenge-backend/api/graph/generated"
	"hiring-challenge-backend/api/graph/model"
	"hiring-challenge-backend/api/internal/auth"
	"hiring-challenge-backend/api/internal/hasura"
	"hiring-challenge-backend/api/internal/requestctx"
	"time"

	"github.com/google/uuid"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.CreateTokenPayload, error) {
	start := time.Now()
	waitUntil := start.Add(1500 * time.Millisecond)
	wait := func() {
		sleep := time.Until(waitUntil)
		if sleep > 0 {
			time.Sleep(sleep)
		}
	}

	user, err := r.HasuraClient.GetUserByEmail(ctx, input.Email)
	if err != nil {
		wait()
		if errors.Is(err, hasura.ErrNotFound) {
			return nil, errors.New(genericLoginError)
		}
		return nil, err
	}

	if !auth.CheckPasswordHash(input.Password, user.PasswordHash) {
		wait()
		return nil, errors.New(genericLoginError)
	}

	member, err := r.HasuraClient.UserHasGroupMembership(ctx, user.ID, user.DefaultGroupID)
	if err != nil {
		return nil, err
	}
	if !member {
		return nil, errors.New("user has no membership in default group")
	}

	identity := auth.UserIdentity{
		UserID:      user.ID,
		GroupID:     user.DefaultGroupID,
		Email:       user.Email,
		DisplayName: user.DisplayName,
	}
	accessToken, expiresAt, err := r.TokenManager.IssueAccessToken(identity)
	if err != nil {
		return nil, err
	}

	if err := r.HasuraClient.UpdateUserLastLogin(ctx, user.ID, time.Now().UTC()); err != nil {
		return nil, fmt.Errorf("update last login: %w", err)
	}

	return &model.CreateTokenPayload{
		Token:          accessToken,
		TokenExpiresAt: int(expiresAt.Unix()),
		UserID:         user.ID.String(),
		GroupID:        user.DefaultGroupID.String(),
		Email:          user.Email,
		DisplayName:    user.DisplayName,
	}, nil
}

// RenewToken is the resolver for the renewToken field.
func (r *mutationResolver) RenewToken(ctx context.Context) (*model.CreateTokenPayload, error) {
	rawClaims, ok := requestctx.TokenClaimsFromContext(ctx)
	if !ok || rawClaims == nil {
		return nil, errors.New("access denied")
	}
	claims, ok := rawClaims.(*auth.TokenClaims)
	if !ok || claims == nil {
		return nil, errors.New("access denied")
	}

	identity := auth.UserIdentity{
		UserID:      claims.UserID,
		GroupID:     claims.GroupID,
		Email:       claims.Email,
		DisplayName: claims.DisplayName,
	}

	accessToken, expiresAt, err := r.TokenManager.IssueAccessToken(identity)
	if err != nil {
		return nil, err
	}

	return &model.CreateTokenPayload{
		Token:          accessToken,
		TokenExpiresAt: int(expiresAt.Unix()),
		UserID:         claims.UserID.String(),
		GroupID:        claims.GroupID.String(),
		Email:          claims.Email,
		DisplayName:    claims.DisplayName,
	}, nil
}

// SwitchGroup is the resolver for the switchGroup field.
func (r *mutationResolver) SwitchGroup(ctx context.Context, groupID string) (*model.CreateTokenPayload, error) {
	rawClaims, ok := requestctx.TokenClaimsFromContext(ctx)
	if !ok || rawClaims == nil {
		return nil, errors.New("access denied")
	}
	claims, ok := rawClaims.(*auth.TokenClaims)
	if !ok || claims == nil {
		return nil, errors.New("access denied")
	}

	nextGroupID, err := uuid.Parse(groupID)
	if err != nil {
		return nil, errors.New("invalid group id")
	}

	member, err := r.HasuraClient.UserHasGroupMembership(ctx, claims.UserID, nextGroupID)
	if err != nil {
		return nil, err
	}
	if !member {
		return nil, errors.New("access denied")
	}

	identity := auth.UserIdentity{
		UserID:      claims.UserID,
		GroupID:     nextGroupID,
		Email:       claims.Email,
		DisplayName: claims.DisplayName,
	}

	accessToken, expiresAt, err := r.TokenManager.IssueAccessToken(identity)
	if err != nil {
		return nil, err
	}

	return &model.CreateTokenPayload{
		Token:          accessToken,
		TokenExpiresAt: int(expiresAt.Unix()),
		UserID:         claims.UserID.String(),
		GroupID:        nextGroupID.String(),
		Email:          claims.Email,
		DisplayName:    claims.DisplayName,
	}, nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "ok", nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
